coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 75%
        threshold: 2%

codecov:
  require_ci_to_pass: yes

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: no

ignore:
  - '**/*.spec.ts'
  - '**/*.e2e.spec.ts'
  - 'test/**/*'
  - 'coverage/**/*'
  - 'dist/**/*'
  - 'node_modules/**/*'
